# Generated by Django 5.0.6 on 2024-09-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=225)),
                ('lastname', models.CharField(max_length=550)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
